name: "Historia de Usuario"
description: "Plantilla para nuevas historias de usuario"
title: "[US] - "
labels: ["user story", "todo"]
body:
  - type: markdown
    attributes:
      value: "### Historia de Usuario"
  - type: textarea
    id: historia
    attributes:
      label: "Descripción"
      placeholder: "Como [usuario], quiero [objetivo] para [beneficio]"
  - type: markdown
    attributes:
      value: "### 📌 Criterios de aceptación"
  - type: textarea
    id: criterios
    attributes:
      label: "Criterios"
      placeholder: "1. ..."
  - type: markdown
    attributes:
      value: "### ⚙️ Notas técnicas"
  - type: textarea
    id: notas
    attributes:
      label: "Detalles técnicos"
      placeholder: "Endpoints, base de datos, validaciones..."
  - type: markdown
    attributes:
      value: "### 🧪 QA / Testing"
  - type: textarea
    id: pruebas
    attributes:
      label: "Casos de prueba"
      placeholder: "QA debe probar..."
